version: "3"
services:
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: example12
    ports:
      - "5432:5432"
  server:
    image: benawad/example:latest
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
